# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-19 00:23
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion

from django.conf import settings

from django_mqtt.publisher.constants import (
    CERT_REQS,
    PROTO_SSL_VERSION,
    PROTO_MQTT_VERSION,
    PROTO_MQTT_CONN_STATUS,
    PROTO_MQTT_QoS,
)

private_location = settings.BASE_DIR
if hasattr(settings, 'MQTT_CERTS_ROOT'):
    private_location = settings.MQTT_CERTS_ROOT


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_mqtt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=1024)),
                ('password', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keepalive', models.IntegerField(default=60)),
                ('clean_session', models.BooleanField(default=True)),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to='publisher.Auth')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='django_mqtt.ClientId')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qos', models.IntegerField(choices=PROTO_MQTT_QoS, default=0)),
                ('payload', models.TextField(blank=True, null=True)),
                ('retain', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Client')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_mqtt.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='SecureConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_certs', models.FileField(
                    storage=django.core.files.storage.FileSystemStorage(location=private_location), upload_to='ca')),
                ('cert_reqs', models.IntegerField(choices=CERT_REQS, default=2)),
                ('tls_version', models.IntegerField(choices=PROTO_SSL_VERSION, default=3)),
                ('certfile', models.FileField(
                    blank=True, null=True,
                    storage=django.core.files.storage.FileSystemStorage(location=private_location), upload_to='certs')),
                ('keyfile', models.FileField(
                    blank=True, null=True,
                    storage=django.core.files.storage.FileSystemStorage(location=private_location), upload_to='keys')),
                ('ciphers', models.CharField(blank=True, default=None, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=1024)),
                ('port', models.IntegerField(default=1883)),
                ('protocol', models.IntegerField(choices=PROTO_MQTT_VERSION, default=4)),
                ('status', models.IntegerField(choices=PROTO_MQTT_CONN_STATUS, default=6)),
                ('secure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='publisher.SecureConf')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('host', 'port')]),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set([('client', 'topic')]),
        ),
    ]
